### PR TITLE
Document minimum MTU for ROKS4

### PR DESCRIPTION
**Pull request by mhmxs**
The lowest value which works on Open Shift 4 is `1450`.

### CODE REVIEW

**Comment by mhmxs** [comment]
@Rachael-Graham Could you please review?

**Comment by Nadine2016** [comment]
@mhmxs can the value be 1450? or is 1449 the first possible value?

**Comment by Nadine2016** [comment]
never mind, saw your first post in here :-)

**Comment by Nadine2016** [comment]
@mhmxs because we use a different source repository to actually change the content. could you review this PR https://github.ibm.com/alchemy-containers/documentation/pull/5664?

**Comment by mhmxs** [comment]
@Nadine2016 sure, thanks

**Comment by Nadine2016** [comment]
closing here as. merged into our source repo

**Pull request closed without merging**
