### PR TITLE
Fix oc expose cmdline

### PR DESCRIPTION
**Pull request by dpkshetty**
Fix `oc expose deployment/hello-world-deployment` to `oc expose deployment/hello-world`

### CODE REVIEW

**Comment by artberger** [comment]
Thanks @dpkshetty , because of the way our repo's are set up, I cannot merge in your branch unfortunately. However, I made the change in our source repo, and the docs will be updated with the next prod push. I'll close this for now. Thanks again for your contribution.

**Comment by dpkshetty** [comment]
@artberger A late thought but can you provide me link to the pull req or commit hash where you made this fix. Also it would have been good if you could credit me in commit message for discovering this issue and proposing the fix as well :)

**Comment by artberger** [comment]
@dpkshetty I added a comment to the commit here, thanks! https://github.com/ibm-cloud-docs/openshift/commit/47f22d6bc11348164e316f6e1edbc4053dddcb0f#r44236289

**Comment by dpkshetty** [comment]
@artberger thanks !

**Pull request closed without merging**
